name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and Deploy
        run: |
          # Install dependencies and build the static assets
          npm install
          npm run build

          # Configure Git
          git config --global user.name "jaztonchern"
          git config --global user.email secrets.EMAIL_ADDRESS

          # Deploy to the gh-pages branch
          git checkout -B gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages


      - name: Send Telegram notification
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_BOT }}
          message: "Deployment to GitHub Pages was successful!"
